'use strict';
const names={weave:'Canonical Weave',highways:'Highways',conveyor:'Conveyor',basic:'Basic',dense:'Dense',shelf:'Shelf',room:'Room',scaledweave:'ScaledWeave'};
const tasks={
 weave:{title:'Exchange positions through shared space',description:'Move every robot from its start to its assigned goal across an open workspace. Crossing routes create conflicts even when each individual path is obstacle-free.'},
 highways:{title:'Share the passages around fixed obstacles',description:'Navigate to assigned goals through the free-space corridors around fixed obstacles. Robots must coordinate where their routes meet and share limited passing room.'},
 conveyor:{title:'Coordinate through narrow lanes',description:'Reach assigned goals around long, parallel obstacles. The layout creates narrow lanes and detours, bringing robots together at shared passages.'},
 basic:{title:'Navigate around scattered obstacles',description:'Move the team to assigned goals through a map of circular obstacles. Each robot must avoid the fixed geometry while coordinating with other moving robots.'},
 dense:{title:'Find room to pass in a crowded map',description:'Reach assigned goals in a denser field of circular obstacles. Less open space makes both obstacle avoidance and robot-to-robot coordination more demanding.'},
 shelf:{title:'Move through a shelf-like layout',description:'Navigate between repeated obstacle structures to reach assigned goals. Robots share constrained routes around the shelves and must coordinate when those routes overlap.'},
 room:{title:'Connect starts and goals across a divided space',description:'Reach assigned goals around room-like obstacle arrangements. The team must navigate the available openings while avoiding obstacles and one another.'},
 scaledweave:{title:'Scale the position-exchange task',description:'Move a larger team between assigned start and goal configurations. The workspace grows with population to preserve feasible endpoints, while crossing routes still require coordination.'}
};
let media=[],environment='weave';
const population=document.querySelector('#population'),method=document.querySelector('#method-choice'),video=document.querySelector('#gallery-video');
function selectEnvironment(key){environment=key;document.querySelectorAll('#environment-tabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.env===key)));const values=[...new Set(media.filter(r=>r.environment===key).map(r=>r.population))].sort((a,b)=>a-b);population.replaceChildren(...values.map(n=>new Option(`${n} robots`,n)));population.value=String(values.at(-1));selectPopulation();}
function selectPopulation(){const available=media.filter(r=>r.environment===environment&&r.population===Number(population.value));method.replaceChildren(...available.map(r=>new Option(environment==='scaledweave'?'Akule · learned sparse proposal':r.method,r.method)));method.value=available.some(r=>r.method==='Akule')?'Akule':available[0].method;selectVideo();}
function selectVideo(){const r=media.find(r=>r.environment===environment&&r.population===Number(population.value)&&r.method===method.value);video.pause();video.poster=r.poster;video.src=r.video;video.load();document.querySelector('#gallery-title').textContent=`Performance on ${names[environment]}, N=${r.population}`;document.querySelector('#gallery-style').textContent=`${r.style} trajectory recording`;document.querySelector('#task-title').textContent=tasks[environment].title;document.querySelector('#gallery-description').textContent=tasks[environment].description;document.querySelector('#task-population').textContent=`${r.population} robots · one assigned goal per robot`;document.querySelector('#gallery-caption').textContent=environment==='scaledweave'?'Akule · learned sparse proposal':`${r.method} · recorded scene ${r.scene_id}`;document.querySelector('#video-link').href=r.video;}
fetch('assets/media-manifest.json').then(r=>{if(!r.ok)throw new Error('Gallery unavailable');return r.json();}).then(rows=>{media=rows;const tabs=document.querySelector('#environment-tabs');for(const [key,name] of Object.entries(names)){if(!media.some(r=>r.environment===key))continue;const b=document.createElement('button');b.type='button';b.dataset.env=key;b.textContent=name;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>selectEnvironment(key));tabs.append(b);}selectEnvironment('weave');}).catch(()=>{document.querySelector('#gallery-title').textContent='Browse the recorded demos';document.querySelector('#gallery-description').textContent='Open the video manifest to access the recordings.';document.querySelector('#video-link').href='assets/media-manifest.json';});
population.addEventListener('change',selectPopulation);method.addEventListener('change',selectVideo);
document.querySelector('#copy-citation').addEventListener('click',async()=>{const text=document.querySelector('#bibtex').textContent;try{await Promise.race([navigator.clipboard.writeText(text),new Promise((_,reject)=>setTimeout(()=>reject(new Error("Clipboard unavailable")),1500))]);document.querySelector('#copy-status').textContent='Citation copied.';}catch{const range=document.createRange();range.selectNodeContents(document.querySelector('#bibtex'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);document.querySelector('#copy-status').textContent='Citation selected. Use your browser’s copy command.';}});
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');const hero=document.querySelector('#hero-video');
if(!reduced.matches&&!navigator.connection?.saveData){new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting)hero.play().catch(()=>{});else hero.pause();}},{threshold:.25}).observe(hero);}
reduced.addEventListener('change',e=>{if(e.matches)hero.pause();});
new IntersectionObserver(entries=>{for(const e of entries)if(!e.isIntersecting)video.pause();},{threshold:.1}).observe(video);
